### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by victorsarbu** [urish/typewiz#22]
Hello!
I tried to use typewiz node but I got the following error: 
/usr/bin/env: ‘node\r’: No such file or directory
I use Linux and I guess \r is the difference between Windows and Linux path.
Thank you!

**Comment by urish** [comment]
Thanks! I have just released typewiz-node 0.4.3 that should fix this

**Comment by victorsarbu** [comment]
Now I get the following errors: 
SyntaxError: Unexpected token } in JSON at position 4712
    at Object.parse (native)
    at parse (/home/victor/.nvm/versions/node/v6.10.3/lib/node_modules/typewiz-node/node_modules/tsconfig/src/tsconfig.ts:195:15)
    at readFileSync (/home/victor/.nvm/versions/node/v6.10.3/lib/node_modules/typewiz-node/node_modules/tsconfig/src/tsconfig.ts:181:10)
    at Object.loadSync (/home/victor/.nvm/versions/node/v6.10.3/lib/node_modules/typewiz-node/node_modules/tsconfig/src/tsconfig.ts:151:18)
    at readConfig (/home/victor/.nvm/versions/node/v6.10.3/lib/node_modules/typewiz-node/node_modules/ts-node/src/index.ts:455:18)
    at Object.register (/home/victor/.nvm/versions/node/v6.10.3/lib/node_modules/typewiz-node/node_modules/ts-node/src/index.ts:205:18)
    at Object.register (/home/victor/.nvm/versions/node/v6.10.3/lib/node_modules/typewiz-node/src/index.ts:16:12)
    at Object.<anonymous> (/home/victor/.nvm/versions/node/v6.10.3/lib/node_modules/typewiz-node/src/typewiz-node.ts:5:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by urish** [comment]
Hi victor, looking at the exception stack trace, it seems like it has a problem with parsing your `tsconfig.json` file. Can you have a look there?

Does your project run with `ts-node`? (typewiz-node is essentially a wrapper around [ts-node](https://www.npmjs.com/package/ts-node))

**Comment by victorsarbu** [comment]
It seems my project doesn't run with ts-node. I use tsc to compile and
execute my files.

2018-03-08 1:25 GMT+02:00 Uri Shaked <notifications@github.com>:

**Comment by urish** [comment]
Do you get a similar errors with ts-node?
